# Generated by Django 5.0.3 on 2024-04-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonateapp', '0003_alter_userprofile_blood_type_needblood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needblood',
            old_name='name',
            new_name='patient_name',
        ),
        migrations.AddField(
            model_name='needblood',
            name='age',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='needblood',
            name='contact_person_name',
            field=models.CharField(default='demo', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='needblood',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
    ]
