# Generated by Django 5.0.3 on 2024-04-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonateapp', '0009_alter_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='needblood',
            name='number_of_units',
            field=models.IntegerField(default=1),
        ),
    ]
