# Generated by Django 5.0.3 on 2024-05-04 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonateapp', '0013_alter_needblood_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needblood',
            name='donated_user',
        ),
        migrations.RemoveField(
            model_name='needblood',
            name='donor_images',
        ),
        migrations.AlterField(
            model_name='donorimages',
            name='need_blood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_images', to='blooddonateapp.needblood'),
        ),
        migrations.CreateModel(
            name='DonorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('donated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_donations', to=settings.AUTH_USER_MODEL)),
                ('donor_images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_need_blood', to='blooddonateapp.donorimages')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
