# Generated by Django 5.0.3 on 2024-03-27 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonateapp', '0002_userprofile_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10),
        ),
        migrations.CreateModel(
            name='NeedBlood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('request_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('donated', models.BooleanField(default=False)),
                ('donated_date', models.DateField(blank=True, null=True)),
                ('donated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_donations', to='blooddonateapp.userprofile')),
                ('requested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='blooddonateapp.userprofile')),
            ],
        ),
    ]
