# Generated by Django 5.0.3 on 2024-04-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonateapp', '0004_rename_name_needblood_patient_name_needblood_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='needblood',
            name='age',
            field=models.IntegerField(),
        ),
    ]
