# Generated by Django 5.0.3 on 2024-04-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonateapp', '0005_userprofile_fcm_token_alter_needblood_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needblood',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
