# Generated by Django 5.0.3 on 2024-04-28 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonateapp', '0011_alter_needblood_donated_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needblood',
            name='donated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
