# Generated by Django 5.0.3 on 2024-10-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonateapp', '0020_alter_userprofile_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorimages',
            name='need_blood',
        ),
        migrations.RemoveField(
            model_name='donormodel',
            name='donor_images',
        ),
        migrations.RemoveField(
            model_name='donormodel',
            name='donated_user',
        ),
        migrations.RemoveField(
            model_name='donormodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='need_blood',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='DonorImages',
        ),
        migrations.DeleteModel(
            name='DonorModel',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
