// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3fI0aiGgGfjKnyWqXYKzY7V7meNrR4hA',
    appId: '1:4708992077:android:5f926e8fb98c4bc56a8804',
    messagingSenderId: '4708992077',
    projectId: 'proplus-logics',
    storageBucket: 'proplus-logics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvqwGezRtRIbiOWJ_D1LwIyjG_mNDutCg',
    appId: '1:4708992077:ios:f20ac86b5c65e7c66a8804',
    messagingSenderId: '4708992077',
    projectId: 'proplus-logics',
    storageBucket: 'proplus-logics.appspot.com',
    androidClientId: '4708992077-krabmtij7tqcipuand6m0v1jauqd5r0e.apps.googleusercontent.com',
    iosClientId: '4708992077-mus500q0rb5q8lj5irrear1758560oib.apps.googleusercontent.com',
    iosBundleId: 'net.hamsahari.blooddonateapp.blooddonateapplication',
  );
}
